// <auto-generated />
using AspNetDemo.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeesApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250603121106_Company added bro")]
    partial class Companyaddedbro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeesApp.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 9817,
                            Name = "ACME"
                        },
                        new
                        {
                            Id = 9898,
                            Name = "EMCA"
                        });
                });

            modelBuilder.Entity("EmployeesApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Money")
                        .HasDefaultValue(0m);

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Money")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 562,
                            Bonus = 0m,
                            CompanyID = 9817,
                            Email = "Anders.Hejlsberg@outlook.com",
                            Name = "Anders Hejlsberg",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 62,
                            Bonus = 0m,
                            CompanyID = 9817,
                            Email = "k.d@outlook.com",
                            Name = "Kathleen Dollard",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 15662,
                            Bonus = 0m,
                            CompanyID = 9898,
                            Email = "Admin.Torgersen@outlook.com",
                            Name = "Mads Torgersen",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("EmployeesApp.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EmployeesApp.Domain.Entities.Company", "company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyID");

                    b.Navigation("company");
                });

            modelBuilder.Entity("EmployeesApp.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
